"""Planner-visible shape; ArtifactSpec and current evidence enforce semantics."""
TEXT=dict(type='string',maxLength=2000)
IDENT=dict(type='string',pattern='^[a-zA-Z][a-zA-Z0-9_-]{0,63}$')
DECIMAL=dict(type='string',maxLength=100,pattern='^-?[0-9]+(?:\\.[0-9]+)?(?:[eE][+-]?[0-9]+)?$')

def obj(properties,required): return dict(type='object',properties=properties,required=required,additionalProperties=False)
REF=obj(dict(asset_id=dict(type='string'),asset_version=dict(type='integer',minimum=1),extraction_id=dict(type='string'),block_id=dict(type='string'),locator=dict(type='object')),['asset_id','asset_version','extraction_id','block_id','locator'])
PROOF=dict(oneOf=[obj(dict(kind=dict(const='quote'),source=REF,quote=TEXT,observation_id=dict(type='string'),segment_id=dict(type='string')),['kind','source','quote']),obj(dict(kind=dict(const='dataset'),dataset_id=dict(type='string'),address=dict(type='string')),['kind','dataset_id','address']),obj(dict(kind=dict(const='computation'),computation_id=dict(type='string')),['kind','computation_id'])])
QUANTITY=obj(dict(value=DECIMAL,lower=DECIMAL,upper=DECIMAL,unit=dict(type='string',minLength=1,maxLength=40)),['value','unit'])
STYLE=obj(dict(background=dict(type='string',pattern='^#[0-9A-Fa-f]{6}$'),foreground=dict(type='string',pattern='^#[0-9A-Fa-f]{6}$'),accent=dict(type='string',pattern='^#[0-9A-Fa-f]{6}$'),muted=dict(type='string',pattern='^#[0-9A-Fa-f]{6}$'),density=dict(enum=['comfortable','compact']),illustration_tone=dict(enum=['calm','playful','formal']),font=dict(const='DejaVuSans')),[])
ELEMENT=obj(dict(id=IDENT,label=dict(type='string',maxLength=300),text=TEXT,status=dict(enum=['observed','confirmed','proposed','unknown','fiction']),quantity=QUANTITY,proof=PROOF,order=dict(type='integer'),when=dict(type='string'),series=dict(type='string')),['id','label','status'])
RELATION=obj(dict(id=IDENT,**{'from':IDENT,'to':IDENT},kind=dict(enum=['sequence','dependency','contrasts','supports','objects','part_of','correlates','claimed_cause','illustrates']),proof=PROOF,label=TEXT),['id','from','to','kind'])
ARTIFACT_SCHEMA=obj(dict(contract=dict(const='artifact-1'),title=dict(type='string',minLength=1,maxLength=300),format=dict(enum=['comparison','timeline','process','roadmap','arguments','statistical','cards','table','teaching']),elements=dict(type='array',minItems=1,maxItems=120,items=ELEMENT),relations=dict(type='array',maxItems=240,items=RELATION),axis=obj(dict(scale=dict(enum=['linear','log']),unit=dict(type='string'),minimum=DECIMAL,maximum=DECIMAL,disclosure=TEXT),['unit']),style=STYLE,illustrations=dict(type='array',maxItems=4,items=dict(type='string',minLength=64,maxLength=64)),questions=dict(type='array',maxItems=12,items=TEXT)),['contract','title','format','elements'])
